version: '3.8'

services:
  frontend:
    image: 77.37.86.76:5000/mon-frontend:latest
    container_name: frontend-container
    environment:
      - PORT=80
    ports:
      - "80:80"  # Redirige le port 80 du conteneur vers le port 80 du VPS
    networks:
      - web

  backend:
    image: 77.37.86.76:5000/mon-backend:latest
    container_name: backend-container
    ports:
      - "3000:3000"
    networks:
      - web
    env_file:
      - $ENV_FILE

networks:
  web:
    external: true
