version: '3.8'

services:
  backend:
    image: mon-backend:latest
    container_name: backend-container
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - $ENV_FILE

  frontend:
    image: mon-frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - "8081:80"
